### ISSUE TITLE
Enhance application UI/UX

### ISSUE THREAD

**Issue by LedZeck** [LedZeck/FunMath#2]
Feel free to make any UI layout improvement

**Comment by pvdsp** [comment]
Can I change the indentation and add a couple of extra spaces? I'll send a pull request asap!

**Comment by pvdsp** [comment]
Small question: do you mean improving code layout or UI of the application?

**Comment by LedZeck** [comment]
@pvdsp the UI indeed;
Sorry about this little mistake

**Comment by pvdsp** [comment]
No problem! ;)

**Comment by pvdsp** [comment]
I'm having some issues trying to run your program. All elements load at the top of the page and are stacked. I tried this with different browsers, reinstalled ionic, deleted and re-cloned your project, without luck.

**Comment by LedZeck** [comment]
Hi, there @pvdsp 

Try to open the browser dev tools and set the view to mobile, then refresh the page.
That should be fix the screen :)
![funmath](https://cloud.githubusercontent.com/assets/7060310/19615366/f26def8a-97dc-11e6-9c37-32acb9a7d292.jpg)

**Comment by pvdsp** [comment]
Sadly, the issue still persists while using mobile view.

![Screenshot](http://i.imgur.com/lVE6ufZ.png)

**Comment by LedZeck** [comment]
@pvdsp I'll try to see what is the bug behind this, tonight.
If I can see what is happening, I'll send another reply here.
Sorry about the delay =/

**Comment by pvdsp** [comment]
No worries! Take your time.

**Comment by mdsecurity** [comment]
im having the same problem
